# --- !Ups

CREATE TABLE USER(
  USER_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  EMAIL VARCHAR(255),
  AVATAR_URL VARCHAR(255),
  ACTIVATED BIT
);

CREATE TABLE LOGIN_INFO (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PROVIDER_ID VARCHAR(255) NOT NULL,
  PROVIDER_KEY VARCHAR(255) NOT NULL
);

CREATE TABLE USER_LOGIN_INFO (
  USER_ID VARCHAR(255) NOT NULL,
  LOGIN_INFO_ID BIGINT NOT NULL
);

CREATE TABLE PASSWORD_INFO (
  HASHER VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  SALT VARCHAR(255),
  LOGIN_INFO_ID BIGINT NOT NULL
);

# --- !Downs

DROP TABLE PASSWORD_INFO;
DROP TABLE USER_LOGIN_INFO;
DROP TABLE LOGIN_INFO;
DROP TABLE USER;